baseURL = "https://abcrypto.co"
title = "ABCrypto"
languageCode = "en-us"
defaultContentLanguage = "en"
theme = "minimal"
#disqusShortname = "username" # delete this to disable disqus comments
pygmentsCodefences = true
pygmentsCodefencesGuessSyntax = true
pygmentsStyle = "pygments"

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[languages]

[languages.en]
    languageName = "English"
    weight = 1
    title = "ABCrypto"
    copyright = "&copy; ABCrypto 2019, all rights reserved."
    contentDir = "content/english"

[languages.en.params]
    author = "omrllm"
    description = "A magnyfing glass on the crypto world."
    githubUsername = "omrllm"
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!

[[menu.main]]
    url = "/topics/"
    name = "Topics"
    weight = 2

[[menu.main]]
    url = "/blog/"
    name = "Blog"
    weight = 3 

[[menu.main]]
    url = "https://github.com/anabcrypto/abcrypto"
    name = "Github"
    weight = 4        

# Footer

[[menu.footer]]
    url = "/about/"
    name = "About"
    weight = 5

[[menu.footer]]
    url = "/termsofuse/"
    name = "Terms of Use"
    weight = 6

[[menu.footer]]
    url = "/contact/"
    name = "Contact"
    weight = 7

# Italian

[languages.it]
    languageName = "Italiano"
    weight = 10
    title = "ABCrypto"
    description = "Una lente d'ingrandimento sul mondo cripto."
    backgroundColor = "white"
    font = "Raleway"
    copyright = "&copy; ABCrypto 2019, tutti i diritti sono riservati."
    contentDir = "content/italian"

[[languages.it.menu.main]]
    url = "/it/argomenti/"
    name = "Argomenti"
    weight = 15

[[languages.it.menu.main]]
    url = "/it/blog/"
    name = "Blog"
    weight = 16

[[languages.it.menu.main]]
    url = "https://github.com/anabcrypto/abcrypto"
    name = "Github"
    weight = 17  

# Footer-Italian

[[languages.it.menu.footer]]
    url = "/it/biografia/"
    name = "Biografia"
    weight = 18

[[languages.it.menu.footer]]
    url = "/it/terminidiuso/"
    name = "Termini di Uso"
    weight = 19

[[languages.it.menu.footer]]
    url = "/it/contattami/"
    name = "Contattami"
    weight = 20

# Arabic

[languages.ar]
    languageName = "العربية"
    weight = 30 
    title = "أب كريبتو"
    description = "عدسة مكبرة علي العالم الكريبتو"
    backgroundColor = "white"
    font = "Raleway"
    copyright = "أب كريبتو ٢٠١٩ ، كل الحقوق محفوظة &copy;"
    contentDir = "content/arabic"

[[languages.ar.menu.main]]
    url = "/ar/argomenti/"
    name = "المواضيع"
    weight = 35

[[languages.ar.menu.main]]
    url = "/ar/blog/"
    name = "مدونة"
    weight = 36

[[languages.ar.menu.main]]
    url = "https://github.com/anabcrypto/abcrypto"
    name = "جيت هاب"
    weight = 37  

# Footer-Arabic

[[languages.ar.menu.footer]]
    url = "/ar/biografia/"
    name = "حول"
    weight = 38

[[languages.ar.menu.footer]]
    url = "/ar/terminidiuso/"
    name = "تعليمات الاستخدام"
    weight = 39

[[languages.ar.menu.footer]]
    url = "/ar/contattami/"
    name = "تواصل"
    weight = 40    