baseURL = "https://getsy.io"
languageCode = "en-us"
title = "ABCrypto"
theme = "minimal"
#disqusShortname = "username" # delete this to disable disqus comments
googleAnalytics = ""

[params]
    author = "omrllm"
    description = "A magnifying glass on the crypto world"
    githubUsername = "omrllm"
    accent = "orange"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/about/"
    name = "About"
    weight = 2

[[menu.main]]
    url = "/posts/"
    name = "Posts"
    weight = 3 

[[menu.main]]
    url = "/termsofuse/"
    name = "Terms of Use"
    weight = 4  
      
[[menu.main]]
    url = "/blog/"
    name = "Blog"
    weight = 5    

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "/"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/abcrypto"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "/"
    name = "reddit"
    weight = 3

[[menu.icon]]
		url = "/"
		name = "language"
		weigth = 4
